# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /nix/store/38cffsqqx823crf1i4bcf6zz1qz1hgpd-cmake-3.30.5/bin/cmake

# The command to remove a file.
RM = /nix/store/38cffsqqx823crf1i4bcf6zz1qz1hgpd-cmake-3.30.5/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/vlvin/Code/C/CLocksVM

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/vlvin/Code/C/CLocksVM

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/nix/store/38cffsqqx823crf1i4bcf6zz1qz1hgpd-cmake-3.30.5/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/nix/store/38cffsqqx823crf1i4bcf6zz1qz1hgpd-cmake-3.30.5/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vlvin/Code/C/CLocksVM/CMakeFiles /home/vlvin/Code/C/CLocksVM//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vlvin/Code/C/CLocksVM/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CLocksCompiler_SRC

# Build rule for target.
CLocksCompiler_SRC: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CLocksCompiler_SRC
.PHONY : CLocksCompiler_SRC

# fast build rule for target.
CLocksCompiler_SRC/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler_SRC.dir/build.make CMakeFiles/CLocksCompiler_SRC.dir/build
.PHONY : CLocksCompiler_SRC/fast

#=============================================================================
# Target rules for targets named CLocksCompiler

# Build rule for target.
CLocksCompiler: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CLocksCompiler
.PHONY : CLocksCompiler

# fast build rule for target.
CLocksCompiler/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler.dir/build.make CMakeFiles/CLocksCompiler.dir/build
.PHONY : CLocksCompiler/fast

src/bitsTricks.o: src/bitsTricks.c.o
.PHONY : src/bitsTricks.o

# target to build an object file
src/bitsTricks.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler_SRC.dir/build.make CMakeFiles/CLocksCompiler_SRC.dir/src/bitsTricks.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler.dir/build.make CMakeFiles/CLocksCompiler.dir/src/bitsTricks.c.o
.PHONY : src/bitsTricks.c.o

src/bitsTricks.i: src/bitsTricks.c.i
.PHONY : src/bitsTricks.i

# target to preprocess a source file
src/bitsTricks.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler_SRC.dir/build.make CMakeFiles/CLocksCompiler_SRC.dir/src/bitsTricks.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler.dir/build.make CMakeFiles/CLocksCompiler.dir/src/bitsTricks.c.i
.PHONY : src/bitsTricks.c.i

src/bitsTricks.s: src/bitsTricks.c.s
.PHONY : src/bitsTricks.s

# target to generate assembly for a file
src/bitsTricks.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler_SRC.dir/build.make CMakeFiles/CLocksCompiler_SRC.dir/src/bitsTricks.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler.dir/build.make CMakeFiles/CLocksCompiler.dir/src/bitsTricks.c.s
.PHONY : src/bitsTricks.c.s

src/debug.o: src/debug.c.o
.PHONY : src/debug.o

# target to build an object file
src/debug.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler_SRC.dir/build.make CMakeFiles/CLocksCompiler_SRC.dir/src/debug.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler.dir/build.make CMakeFiles/CLocksCompiler.dir/src/debug.c.o
.PHONY : src/debug.c.o

src/debug.i: src/debug.c.i
.PHONY : src/debug.i

# target to preprocess a source file
src/debug.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler_SRC.dir/build.make CMakeFiles/CLocksCompiler_SRC.dir/src/debug.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler.dir/build.make CMakeFiles/CLocksCompiler.dir/src/debug.c.i
.PHONY : src/debug.c.i

src/debug.s: src/debug.c.s
.PHONY : src/debug.s

# target to generate assembly for a file
src/debug.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler_SRC.dir/build.make CMakeFiles/CLocksCompiler_SRC.dir/src/debug.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler.dir/build.make CMakeFiles/CLocksCompiler.dir/src/debug.c.s
.PHONY : src/debug.c.s

src/loxCLI.o: src/loxCLI.c.o
.PHONY : src/loxCLI.o

# target to build an object file
src/loxCLI.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler_SRC.dir/build.make CMakeFiles/CLocksCompiler_SRC.dir/src/loxCLI.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler.dir/build.make CMakeFiles/CLocksCompiler.dir/src/loxCLI.c.o
.PHONY : src/loxCLI.c.o

src/loxCLI.i: src/loxCLI.c.i
.PHONY : src/loxCLI.i

# target to preprocess a source file
src/loxCLI.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler_SRC.dir/build.make CMakeFiles/CLocksCompiler_SRC.dir/src/loxCLI.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler.dir/build.make CMakeFiles/CLocksCompiler.dir/src/loxCLI.c.i
.PHONY : src/loxCLI.c.i

src/loxCLI.s: src/loxCLI.c.s
.PHONY : src/loxCLI.s

# target to generate assembly for a file
src/loxCLI.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler_SRC.dir/build.make CMakeFiles/CLocksCompiler_SRC.dir/src/loxCLI.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler.dir/build.make CMakeFiles/CLocksCompiler.dir/src/loxCLI.c.s
.PHONY : src/loxCLI.c.s

src/loxChunk.o: src/loxChunk.c.o
.PHONY : src/loxChunk.o

# target to build an object file
src/loxChunk.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler_SRC.dir/build.make CMakeFiles/CLocksCompiler_SRC.dir/src/loxChunk.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler.dir/build.make CMakeFiles/CLocksCompiler.dir/src/loxChunk.c.o
.PHONY : src/loxChunk.c.o

src/loxChunk.i: src/loxChunk.c.i
.PHONY : src/loxChunk.i

# target to preprocess a source file
src/loxChunk.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler_SRC.dir/build.make CMakeFiles/CLocksCompiler_SRC.dir/src/loxChunk.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler.dir/build.make CMakeFiles/CLocksCompiler.dir/src/loxChunk.c.i
.PHONY : src/loxChunk.c.i

src/loxChunk.s: src/loxChunk.c.s
.PHONY : src/loxChunk.s

# target to generate assembly for a file
src/loxChunk.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler_SRC.dir/build.make CMakeFiles/CLocksCompiler_SRC.dir/src/loxChunk.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler.dir/build.make CMakeFiles/CLocksCompiler.dir/src/loxChunk.c.s
.PHONY : src/loxChunk.c.s

src/loxCompiler.o: src/loxCompiler.c.o
.PHONY : src/loxCompiler.o

# target to build an object file
src/loxCompiler.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler_SRC.dir/build.make CMakeFiles/CLocksCompiler_SRC.dir/src/loxCompiler.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler.dir/build.make CMakeFiles/CLocksCompiler.dir/src/loxCompiler.c.o
.PHONY : src/loxCompiler.c.o

src/loxCompiler.i: src/loxCompiler.c.i
.PHONY : src/loxCompiler.i

# target to preprocess a source file
src/loxCompiler.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler_SRC.dir/build.make CMakeFiles/CLocksCompiler_SRC.dir/src/loxCompiler.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler.dir/build.make CMakeFiles/CLocksCompiler.dir/src/loxCompiler.c.i
.PHONY : src/loxCompiler.c.i

src/loxCompiler.s: src/loxCompiler.c.s
.PHONY : src/loxCompiler.s

# target to generate assembly for a file
src/loxCompiler.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler_SRC.dir/build.make CMakeFiles/CLocksCompiler_SRC.dir/src/loxCompiler.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler.dir/build.make CMakeFiles/CLocksCompiler.dir/src/loxCompiler.c.s
.PHONY : src/loxCompiler.c.s

src/loxErrors.o: src/loxErrors.c.o
.PHONY : src/loxErrors.o

# target to build an object file
src/loxErrors.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler_SRC.dir/build.make CMakeFiles/CLocksCompiler_SRC.dir/src/loxErrors.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler.dir/build.make CMakeFiles/CLocksCompiler.dir/src/loxErrors.c.o
.PHONY : src/loxErrors.c.o

src/loxErrors.i: src/loxErrors.c.i
.PHONY : src/loxErrors.i

# target to preprocess a source file
src/loxErrors.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler_SRC.dir/build.make CMakeFiles/CLocksCompiler_SRC.dir/src/loxErrors.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler.dir/build.make CMakeFiles/CLocksCompiler.dir/src/loxErrors.c.i
.PHONY : src/loxErrors.c.i

src/loxErrors.s: src/loxErrors.c.s
.PHONY : src/loxErrors.s

# target to generate assembly for a file
src/loxErrors.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler_SRC.dir/build.make CMakeFiles/CLocksCompiler_SRC.dir/src/loxErrors.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler.dir/build.make CMakeFiles/CLocksCompiler.dir/src/loxErrors.c.s
.PHONY : src/loxErrors.c.s

src/loxLineTracker.o: src/loxLineTracker.c.o
.PHONY : src/loxLineTracker.o

# target to build an object file
src/loxLineTracker.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler_SRC.dir/build.make CMakeFiles/CLocksCompiler_SRC.dir/src/loxLineTracker.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler.dir/build.make CMakeFiles/CLocksCompiler.dir/src/loxLineTracker.c.o
.PHONY : src/loxLineTracker.c.o

src/loxLineTracker.i: src/loxLineTracker.c.i
.PHONY : src/loxLineTracker.i

# target to preprocess a source file
src/loxLineTracker.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler_SRC.dir/build.make CMakeFiles/CLocksCompiler_SRC.dir/src/loxLineTracker.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler.dir/build.make CMakeFiles/CLocksCompiler.dir/src/loxLineTracker.c.i
.PHONY : src/loxLineTracker.c.i

src/loxLineTracker.s: src/loxLineTracker.c.s
.PHONY : src/loxLineTracker.s

# target to generate assembly for a file
src/loxLineTracker.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler_SRC.dir/build.make CMakeFiles/CLocksCompiler_SRC.dir/src/loxLineTracker.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler.dir/build.make CMakeFiles/CLocksCompiler.dir/src/loxLineTracker.c.s
.PHONY : src/loxLineTracker.c.s

src/loxMemory.o: src/loxMemory.c.o
.PHONY : src/loxMemory.o

# target to build an object file
src/loxMemory.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler_SRC.dir/build.make CMakeFiles/CLocksCompiler_SRC.dir/src/loxMemory.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler.dir/build.make CMakeFiles/CLocksCompiler.dir/src/loxMemory.c.o
.PHONY : src/loxMemory.c.o

src/loxMemory.i: src/loxMemory.c.i
.PHONY : src/loxMemory.i

# target to preprocess a source file
src/loxMemory.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler_SRC.dir/build.make CMakeFiles/CLocksCompiler_SRC.dir/src/loxMemory.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler.dir/build.make CMakeFiles/CLocksCompiler.dir/src/loxMemory.c.i
.PHONY : src/loxMemory.c.i

src/loxMemory.s: src/loxMemory.c.s
.PHONY : src/loxMemory.s

# target to generate assembly for a file
src/loxMemory.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler_SRC.dir/build.make CMakeFiles/CLocksCompiler_SRC.dir/src/loxMemory.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler.dir/build.make CMakeFiles/CLocksCompiler.dir/src/loxMemory.c.s
.PHONY : src/loxMemory.c.s

src/loxObject.o: src/loxObject.c.o
.PHONY : src/loxObject.o

# target to build an object file
src/loxObject.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler_SRC.dir/build.make CMakeFiles/CLocksCompiler_SRC.dir/src/loxObject.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler.dir/build.make CMakeFiles/CLocksCompiler.dir/src/loxObject.c.o
.PHONY : src/loxObject.c.o

src/loxObject.i: src/loxObject.c.i
.PHONY : src/loxObject.i

# target to preprocess a source file
src/loxObject.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler_SRC.dir/build.make CMakeFiles/CLocksCompiler_SRC.dir/src/loxObject.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler.dir/build.make CMakeFiles/CLocksCompiler.dir/src/loxObject.c.i
.PHONY : src/loxObject.c.i

src/loxObject.s: src/loxObject.c.s
.PHONY : src/loxObject.s

# target to generate assembly for a file
src/loxObject.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler_SRC.dir/build.make CMakeFiles/CLocksCompiler_SRC.dir/src/loxObject.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler.dir/build.make CMakeFiles/CLocksCompiler.dir/src/loxObject.c.s
.PHONY : src/loxObject.c.s

src/loxParser.o: src/loxParser.c.o
.PHONY : src/loxParser.o

# target to build an object file
src/loxParser.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler_SRC.dir/build.make CMakeFiles/CLocksCompiler_SRC.dir/src/loxParser.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler.dir/build.make CMakeFiles/CLocksCompiler.dir/src/loxParser.c.o
.PHONY : src/loxParser.c.o

src/loxParser.i: src/loxParser.c.i
.PHONY : src/loxParser.i

# target to preprocess a source file
src/loxParser.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler_SRC.dir/build.make CMakeFiles/CLocksCompiler_SRC.dir/src/loxParser.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler.dir/build.make CMakeFiles/CLocksCompiler.dir/src/loxParser.c.i
.PHONY : src/loxParser.c.i

src/loxParser.s: src/loxParser.c.s
.PHONY : src/loxParser.s

# target to generate assembly for a file
src/loxParser.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler_SRC.dir/build.make CMakeFiles/CLocksCompiler_SRC.dir/src/loxParser.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler.dir/build.make CMakeFiles/CLocksCompiler.dir/src/loxParser.c.s
.PHONY : src/loxParser.c.s

src/loxScanner.o: src/loxScanner.c.o
.PHONY : src/loxScanner.o

# target to build an object file
src/loxScanner.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler_SRC.dir/build.make CMakeFiles/CLocksCompiler_SRC.dir/src/loxScanner.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler.dir/build.make CMakeFiles/CLocksCompiler.dir/src/loxScanner.c.o
.PHONY : src/loxScanner.c.o

src/loxScanner.i: src/loxScanner.c.i
.PHONY : src/loxScanner.i

# target to preprocess a source file
src/loxScanner.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler_SRC.dir/build.make CMakeFiles/CLocksCompiler_SRC.dir/src/loxScanner.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler.dir/build.make CMakeFiles/CLocksCompiler.dir/src/loxScanner.c.i
.PHONY : src/loxScanner.c.i

src/loxScanner.s: src/loxScanner.c.s
.PHONY : src/loxScanner.s

# target to generate assembly for a file
src/loxScanner.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler_SRC.dir/build.make CMakeFiles/CLocksCompiler_SRC.dir/src/loxScanner.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler.dir/build.make CMakeFiles/CLocksCompiler.dir/src/loxScanner.c.s
.PHONY : src/loxScanner.c.s

src/loxStack.o: src/loxStack.c.o
.PHONY : src/loxStack.o

# target to build an object file
src/loxStack.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler_SRC.dir/build.make CMakeFiles/CLocksCompiler_SRC.dir/src/loxStack.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler.dir/build.make CMakeFiles/CLocksCompiler.dir/src/loxStack.c.o
.PHONY : src/loxStack.c.o

src/loxStack.i: src/loxStack.c.i
.PHONY : src/loxStack.i

# target to preprocess a source file
src/loxStack.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler_SRC.dir/build.make CMakeFiles/CLocksCompiler_SRC.dir/src/loxStack.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler.dir/build.make CMakeFiles/CLocksCompiler.dir/src/loxStack.c.i
.PHONY : src/loxStack.c.i

src/loxStack.s: src/loxStack.c.s
.PHONY : src/loxStack.s

# target to generate assembly for a file
src/loxStack.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler_SRC.dir/build.make CMakeFiles/CLocksCompiler_SRC.dir/src/loxStack.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler.dir/build.make CMakeFiles/CLocksCompiler.dir/src/loxStack.c.s
.PHONY : src/loxStack.c.s

src/loxToken.o: src/loxToken.c.o
.PHONY : src/loxToken.o

# target to build an object file
src/loxToken.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler_SRC.dir/build.make CMakeFiles/CLocksCompiler_SRC.dir/src/loxToken.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler.dir/build.make CMakeFiles/CLocksCompiler.dir/src/loxToken.c.o
.PHONY : src/loxToken.c.o

src/loxToken.i: src/loxToken.c.i
.PHONY : src/loxToken.i

# target to preprocess a source file
src/loxToken.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler_SRC.dir/build.make CMakeFiles/CLocksCompiler_SRC.dir/src/loxToken.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler.dir/build.make CMakeFiles/CLocksCompiler.dir/src/loxToken.c.i
.PHONY : src/loxToken.c.i

src/loxToken.s: src/loxToken.c.s
.PHONY : src/loxToken.s

# target to generate assembly for a file
src/loxToken.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler_SRC.dir/build.make CMakeFiles/CLocksCompiler_SRC.dir/src/loxToken.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler.dir/build.make CMakeFiles/CLocksCompiler.dir/src/loxToken.c.s
.PHONY : src/loxToken.c.s

src/loxVM.o: src/loxVM.c.o
.PHONY : src/loxVM.o

# target to build an object file
src/loxVM.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler_SRC.dir/build.make CMakeFiles/CLocksCompiler_SRC.dir/src/loxVM.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler.dir/build.make CMakeFiles/CLocksCompiler.dir/src/loxVM.c.o
.PHONY : src/loxVM.c.o

src/loxVM.i: src/loxVM.c.i
.PHONY : src/loxVM.i

# target to preprocess a source file
src/loxVM.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler_SRC.dir/build.make CMakeFiles/CLocksCompiler_SRC.dir/src/loxVM.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler.dir/build.make CMakeFiles/CLocksCompiler.dir/src/loxVM.c.i
.PHONY : src/loxVM.c.i

src/loxVM.s: src/loxVM.c.s
.PHONY : src/loxVM.s

# target to generate assembly for a file
src/loxVM.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler_SRC.dir/build.make CMakeFiles/CLocksCompiler_SRC.dir/src/loxVM.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler.dir/build.make CMakeFiles/CLocksCompiler.dir/src/loxVM.c.s
.PHONY : src/loxVM.c.s

src/loxValue.o: src/loxValue.c.o
.PHONY : src/loxValue.o

# target to build an object file
src/loxValue.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler_SRC.dir/build.make CMakeFiles/CLocksCompiler_SRC.dir/src/loxValue.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler.dir/build.make CMakeFiles/CLocksCompiler.dir/src/loxValue.c.o
.PHONY : src/loxValue.c.o

src/loxValue.i: src/loxValue.c.i
.PHONY : src/loxValue.i

# target to preprocess a source file
src/loxValue.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler_SRC.dir/build.make CMakeFiles/CLocksCompiler_SRC.dir/src/loxValue.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler.dir/build.make CMakeFiles/CLocksCompiler.dir/src/loxValue.c.i
.PHONY : src/loxValue.c.i

src/loxValue.s: src/loxValue.c.s
.PHONY : src/loxValue.s

# target to generate assembly for a file
src/loxValue.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler_SRC.dir/build.make CMakeFiles/CLocksCompiler_SRC.dir/src/loxValue.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler.dir/build.make CMakeFiles/CLocksCompiler.dir/src/loxValue.c.s
.PHONY : src/loxValue.c.s

src/loxValueArray.o: src/loxValueArray.c.o
.PHONY : src/loxValueArray.o

# target to build an object file
src/loxValueArray.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler_SRC.dir/build.make CMakeFiles/CLocksCompiler_SRC.dir/src/loxValueArray.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler.dir/build.make CMakeFiles/CLocksCompiler.dir/src/loxValueArray.c.o
.PHONY : src/loxValueArray.c.o

src/loxValueArray.i: src/loxValueArray.c.i
.PHONY : src/loxValueArray.i

# target to preprocess a source file
src/loxValueArray.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler_SRC.dir/build.make CMakeFiles/CLocksCompiler_SRC.dir/src/loxValueArray.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler.dir/build.make CMakeFiles/CLocksCompiler.dir/src/loxValueArray.c.i
.PHONY : src/loxValueArray.c.i

src/loxValueArray.s: src/loxValueArray.c.s
.PHONY : src/loxValueArray.s

# target to generate assembly for a file
src/loxValueArray.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler_SRC.dir/build.make CMakeFiles/CLocksCompiler_SRC.dir/src/loxValueArray.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler.dir/build.make CMakeFiles/CLocksCompiler.dir/src/loxValueArray.c.s
.PHONY : src/loxValueArray.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler.dir/build.make CMakeFiles/CLocksCompiler.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler.dir/build.make CMakeFiles/CLocksCompiler.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLocksCompiler.dir/build.make CMakeFiles/CLocksCompiler.dir/src/main.c.s
.PHONY : src/main.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... CLocksCompiler"
	@echo "... CLocksCompiler_SRC"
	@echo "... src/bitsTricks.o"
	@echo "... src/bitsTricks.i"
	@echo "... src/bitsTricks.s"
	@echo "... src/debug.o"
	@echo "... src/debug.i"
	@echo "... src/debug.s"
	@echo "... src/loxCLI.o"
	@echo "... src/loxCLI.i"
	@echo "... src/loxCLI.s"
	@echo "... src/loxChunk.o"
	@echo "... src/loxChunk.i"
	@echo "... src/loxChunk.s"
	@echo "... src/loxCompiler.o"
	@echo "... src/loxCompiler.i"
	@echo "... src/loxCompiler.s"
	@echo "... src/loxErrors.o"
	@echo "... src/loxErrors.i"
	@echo "... src/loxErrors.s"
	@echo "... src/loxLineTracker.o"
	@echo "... src/loxLineTracker.i"
	@echo "... src/loxLineTracker.s"
	@echo "... src/loxMemory.o"
	@echo "... src/loxMemory.i"
	@echo "... src/loxMemory.s"
	@echo "... src/loxObject.o"
	@echo "... src/loxObject.i"
	@echo "... src/loxObject.s"
	@echo "... src/loxParser.o"
	@echo "... src/loxParser.i"
	@echo "... src/loxParser.s"
	@echo "... src/loxScanner.o"
	@echo "... src/loxScanner.i"
	@echo "... src/loxScanner.s"
	@echo "... src/loxStack.o"
	@echo "... src/loxStack.i"
	@echo "... src/loxStack.s"
	@echo "... src/loxToken.o"
	@echo "... src/loxToken.i"
	@echo "... src/loxToken.s"
	@echo "... src/loxVM.o"
	@echo "... src/loxVM.i"
	@echo "... src/loxVM.s"
	@echo "... src/loxValue.o"
	@echo "... src/loxValue.i"
	@echo "... src/loxValue.s"
	@echo "... src/loxValueArray.o"
	@echo "... src/loxValueArray.i"
	@echo "... src/loxValueArray.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

